//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accessorie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patch
    {
        public int IdPatch { get; set; }
        public Nullable<int> IdDetail { get; set; }
        public Nullable<int> IdWarehouse { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public Nullable<int> IdRepairer { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Repairer Repairer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
