//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accessorie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patch
    {
        public int IdPatch { get; set; }
        public Nullable<int> IdDetail { get; set; }
        public Nullable<int> IdWarehouse { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public Nullable<int> IdRepairer { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Repairer Repairer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
